baseURL = 'https://www.fsv-unterjesingen.de/'
languageCode = 'de-de'
title = 'FSV Unterjesingen'

[params]
clubName = 'Flugsportverein Unterjesingen e.V.'
tagline = 'Segelflug, Motorsegler und Gemeinschaft am SchÃ¶nbuchrand'
ctaText = 'Mitfliegen & Mitglied werden'
ctaLink = '/kontakt/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Start'
    pageRef = '/'
    weight = 1
  [[menu.main]]
    name = 'Segelflug'
    url = '#'
    identifier = 'segelflug'
    weight = 2
  [[menu.main]]
    name = 'Allgemeines'
    pageRef = '/segelflug'
    parent = 'segelflug'
    weight = 1
  [[menu.main]]
    name = 'Fliegen lernen'
    pageRef = '/fliegen-lernen'
    parent = 'segelflug'
    weight = 2
  [[menu.main]]
    name = 'Streckenflug'
    pageRef = '/streckenflug'
    parent = 'segelflug'
    weight = 3
  [[menu.main]]
    name = 'Verein'
    pageRef = '/verein'
    weight = 4
  [[menu.main]]
    name = 'FAQ'
    pageRef = '/faq'
    weight = 5
  [[menu.main]]
    name = 'Kontakt'
    pageRef = '/kontakt'
    weight = 6
