baseURL = 'https://www.fsv-unterjesingen.de/'
languageCode = 'de-de'
title = 'FSV Unterjesingen'

[params]
clubName = 'Flugsportverein Unterjesingen e.V.'
tagline = 'Segelflug, Motorsegler und Gemeinschaft am Sch√∂nbuchrand'
ctaText = 'Mitfliegen & Mitglied werden'
ctaLink = '/kontakt/'

[menu]
  [[menu.main]]
    name = 'Start'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Fliegen lernen'
    url = '/fliegen-lernen/'
    weight = 2
  [[menu.main]]
    name = 'Verein'
    url = '/verein/'
    weight = 3
  [[menu.main]]
    name = 'Streckenflug'
    url = '/streckenflug/'
    weight = 4
  [[menu.main]]
    name = 'FAQ'
    url = '/faq/'
    weight = 5
  [[menu.main]]
    name = 'Kontakt'
    url = '/kontakt/'
    weight = 6
